/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author salva
 */
import Vistas.Deducciones;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class PaginaPrincipal extends javax.swing.JFrame {

    Connection con;

    public PaginaPrincipal(Connection con) {
        con = con;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private PaginaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnUsuarios = new javax.swing.JButton();
        btnFormasPago = new javax.swing.JButton();
        btnPeriodos = new javax.swing.JButton();
        btnPercepciones = new javax.swing.JButton();
        btnDeducciones = new javax.swing.JButton();
        btnCiudades = new javax.swing.JButton();
        btnEstados = new javax.swing.JButton();
        btnDepartamentos = new javax.swing.JButton();
        btnTurnos = new javax.swing.JButton();
        btnPuestos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUsuarios.setBackground(new java.awt.Color(51, 153, 255));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/perfil.png"))); // NOI18N
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.setBorder(null);
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUsuarios.setFocusPainted(false);
        btnUsuarios.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/perfil.png"))); // NOI18N
        btnUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/perfil.png"))); // NOI18N
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnFormasPago.setBackground(new java.awt.Color(51, 153, 255));
        btnFormasPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/tarjeta-de-credito.png"))); // NOI18N
        btnFormasPago.setText("FORMAS DE PAGO");
        btnFormasPago.setBorder(null);
        btnFormasPago.setBorderPainted(false);
        btnFormasPago.setContentAreaFilled(false);
        btnFormasPago.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFormasPago.setFocusPainted(false);
        btnFormasPago.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/tarjeta-de-credito.png"))); // NOI18N
        btnFormasPago.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/tarjeta-de-credito.png"))); // NOI18N
        btnFormasPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormasPagoActionPerformed(evt);
            }
        });

        btnPeriodos.setBackground(new java.awt.Color(51, 153, 255));
        btnPeriodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/periodico.png"))); // NOI18N
        btnPeriodos.setText("PERIODOS");
        btnPeriodos.setBorder(null);
        btnPeriodos.setBorderPainted(false);
        btnPeriodos.setContentAreaFilled(false);
        btnPeriodos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPeriodos.setFocusPainted(false);
        btnPeriodos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/periodico.png"))); // NOI18N
        btnPeriodos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/periodico.png"))); // NOI18N
        btnPeriodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeriodosActionPerformed(evt);
            }
        });

        btnPercepciones.setBackground(new java.awt.Color(51, 153, 255));
        btnPercepciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/percepcion-de-profundidad.png"))); // NOI18N
        btnPercepciones.setText("PERCEPCIONES");
        btnPercepciones.setBorder(null);
        btnPercepciones.setBorderPainted(false);
        btnPercepciones.setContentAreaFilled(false);
        btnPercepciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPercepciones.setFocusPainted(false);
        btnPercepciones.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/percepcion-de-profundidad.png"))); // NOI18N
        btnPercepciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/percepcion-de-profundidad.png"))); // NOI18N
        btnPercepciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercepcionesActionPerformed(evt);
            }
        });

        btnDeducciones.setBackground(new java.awt.Color(51, 153, 255));
        btnDeducciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/calcular-impuestos.png"))); // NOI18N
        btnDeducciones.setText("DEDUCCIONES");
        btnDeducciones.setBorder(null);
        btnDeducciones.setBorderPainted(false);
        btnDeducciones.setContentAreaFilled(false);
        btnDeducciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDeducciones.setFocusPainted(false);
        btnDeducciones.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/calcular-impuestos.png"))); // NOI18N
        btnDeducciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/calcular-impuestos.png"))); // NOI18N
        btnDeducciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeduccionesMouseClicked(evt);
            }
        });

        btnCiudades.setText("Ciudades");
        btnCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiudadesActionPerformed(evt);
            }
        });

        btnEstados.setText("Estados");
        btnEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadosActionPerformed(evt);
            }
        });

        btnDepartamentos.setText("Departamentos");
        btnDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartamentosActionPerformed(evt);
            }
        });

        btnTurnos.setText("Turnos");
        btnTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnosActionPerformed(evt);
            }
        });

        btnPuestos.setText("Puestos");
        btnPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuestosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUsuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPeriodos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeducciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFormasPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPercepciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCiudades)
                                .addGap(18, 18, 18)
                                .addComponent(btnEstados)
                                .addGap(18, 18, 18)
                                .addComponent(btnDepartamentos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTurnos)
                                .addGap(18, 18, 18)
                                .addComponent(btnPuestos)))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFormasPago, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPercepciones, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnDeducciones, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCiudades)
                    .addComponent(btnEstados)
                    .addComponent(btnDepartamentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTurnos)
                    .addComponent(btnPuestos)))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed

    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnDeduccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeduccionesMouseClicked
        Deducciones d = new Deducciones();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDeduccionesMouseClicked

    private void btnCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiudadesActionPerformed
        Cuidades ciudades = new Cuidades();
        ciudades.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCiudadesActionPerformed

    private void btnEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadosActionPerformed
        Estados estados = new Estados();
        estados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEstadosActionPerformed

    private void btnDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartamentosActionPerformed
        Departamentos departamentos = new Departamentos();
        departamentos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDepartamentosActionPerformed

    private void btnTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnosActionPerformed
        Turnos turnos = new Turnos();
        turnos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTurnosActionPerformed

    private void btnPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuestosActionPerformed
        Puestos puestos = new Puestos();
        puestos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPuestosActionPerformed

    private void btnPeriodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeriodosActionPerformed
        Periodos pe = new Periodos();
        pe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPeriodosActionPerformed

    private void btnFormasPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormasPagoActionPerformed
        FormasDePago fdp = new FormasDePago();
        fdp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFormasPagoActionPerformed

    private void btnPercepcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercepcionesActionPerformed
        Percepciones per = new Percepciones();
        per.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPercepcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCiudades;
    private javax.swing.JButton btnDeducciones;
    private javax.swing.JButton btnDepartamentos;
    private javax.swing.JButton btnEstados;
    private javax.swing.JButton btnFormasPago;
    private javax.swing.JButton btnPercepciones;
    private javax.swing.JButton btnPeriodos;
    private javax.swing.JButton btnPuestos;
    private javax.swing.JButton btnTurnos;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
